# golangci-lint configuration
run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
  build-tags:
    - static

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/omegaup/quark
  govet:
    shadow: true
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - dupl

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
      - misspell
      severity: warning